config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: 'products#index'
  get 'bon', to: 'pages#bon'
  resources :products, only: [:index]
  resources :orders, only: [:index, :new]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  monetize :amount_cents

  # validations:
  validates :first_name, presence: { message: "Veuillez mettre le prénom de la personne qui volera" }
  validates :last_name, presence: { message: "Veuillez mettre le nom de la personne qui volera" }
  validates :email, presence: { message: "Veuillez mettre un email" }
  validates :email, format: {:with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, :message => "Veuillez renseigner un email valide" }
  validates :cgv, acceptance: { message: "\n Veuillez confirmer avoir pris connaissance des conditions générales de vente" }

  #scopes:
  scope :status, -> (status) { where state: status }

  #methodes:
  def creation_bon
    parametres = { first_name: self.first_name,
                    last_name: self.last_name,
                    product_name: self.product_name,
                    video: self.video
                  }
    string_of_param = parametres.reduce("") { |sum,(key,val)| "#{sum}&#{key}=#{val}"}

    if Rails.env == "development"
      html = "http://localhost:3000/bon?#{string_of_param}"
    else
      html = "https://www.secure-lesgensdair.com/bon?#{string_of_param}"
    end
    kit = PDFKit.new(html, :page_size => 'Letter',
                            :margin_top => '0.0in',
                            :margin_right => '0.0in',
                            :margin_bottom => '0.0in',
                            :margin_left => '0.0in')

    file = kit.to_file(Rails.root.join('tmp','bon-parapente.pdf'))
  end
end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents  # or :price_pennies
  validates :name, presence: true
  validates :sku, presence: true
  validates :sku, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

    include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "Vous n'êtes pas autorisé à effectuer cette action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :create, :new]

  def index
    order = Order.new
    authorize order
    @orders = policy_scope(Order).order(created_at: :desc)
    filtering_params(params).each do |key, value|
      @orders = @orders.public_send(key, value) if value.present?
    end
  end

  def new
    @order = Order.new
    authorize @order
    @products = Product.all
  end

  def show
    @order = Order.where(state: 'payé').find(params[:id])
    authorize @order
  end

  def create
    raise
    @products = policy_scope(Product)
    @product = Product.find_by(sku: params[:order][:product_sku])
    order_params[:video] == "1" ? amount_to_pay = @product.price + Money.new(2000, 'EUR') : amount_to_pay = @product.price
    @order  = Order.create(
      product_sku: @product.sku,
      product_name: @product.name,
      amount: amount_to_pay,
      state: 'en attente',
      first_name: order_params[:first_name].capitalize,
      last_name: order_params[:last_name].capitalize,
      email: order_params[:email],
      video: order_params[:video],
      cgv: order_params[:cgv])
    authorize @order
    if @order.save
      redirect_to new_order_payment_path(@order)
    else
      render "products/index"
    end
  end

  private

  def order_params
    params.require(:order).permit(:email, :first_name, :last_name, :video, :product_name, :cgv)
  end

  # A list of the param names that can be used for filtering the order list
  def filtering_params(params)
    params.slice(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home , :bon]

  def home
  end

  def bon
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @product_name = params[:product_name]
    @video = params[:video]
    render :layout => false
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents, # or amount_pennies
      description:  "Règlement pour un #{@order.product_name}. Merci pour votre confiance. (Commande numéro #{@order.id})",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'payé')
    @order.creation_bon
    BuyerMailer.thanks(@order).deliver_now
    redirect_to order_path(@order)

  rescue Stripe::CardError => e
    @order.state = 'erreur lors du paiement'
    @order.save
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

private
  # before_actions :
  def set_order
    @order = Order.where.not(state: 'payé').find(params[:order_id])
    authorize @order
  end
  # -- end of before_actions
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @products = policy_scope(Product)
    @order = Order.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Les Gens d'Air | École de parapente en Chartreuse</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="shortcut icon" type="image/x-icon" href="http://www.lesgensdair.com/wp-content/themes/parapente/img/fav.png">
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= link_to "http://www.lesgensdair.com/" do %>
      <%= image_tag "logo.png", id: "logo", class: "hidden-xs"%>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="introduction-title">
  <div class="admin-options">
    <h3>Liste des commandes : (utilisateur connecté : <%= current_user.email %>)</h3>
    <h4>
      <%= link_to edit_user_registration_path do %>
        <i class="fa fa-key" aria-hidden="true"></i>
      <% end %>
      &nbsp;
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-power-off" aria-hidden="true"></i>
      <% end %>
    </h4>
  </div>
</div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="card">
          <div class="filters">
            <%= form_tag(orders_path, :method => "get", class: "search-form form-inline") do %>
              <%= label_tag "status", "Status : " %>
              <% status = params[:status]%>
              <%= select_tag "status", "<option value="">Tous</option><option #{'selected' if status == "payé"}>payé</option><option #{'selected' if status == "en attente"}>en attente</option><option #{'selected' if status == "erreur lors du paiement"}>erreur lors du paiement</option>".html_safe  %>
              <button type="submit" class="btn btn-primary">Mettre à jour</button>
            <% end %>
            <br>
          </div>
          <div class="card-content">
            <table class="table">
              <thead>
                <tr>
                  <th>N°</th>
                  <th>Date</th>
                  <th>Email</th>
                  <th>Prénom</th>
                  <th>Nom</th>
                  <th>Prestation</th>
                  <th>Video?</th>
                  <th>Montant</th>
                  <th>Paiement</th>
                </tr>
              </thead>
              <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td><%= order.id %></td>
                    <td><%= order.created_at.strftime("%d/%m/%Y") %></td>
                    <td><%= order.email %></td>
                    <td><%= order.first_name %></td>
                    <td><%= order.last_name %></td>
                    <td><%= order.product_name %></td>
                    <td><%= order.video ? "oui" : "non" %></td>
                    <td><%= order.amount %></td>
                    <td><%= order.state %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/orders/new.html.erb
<div class="introduction-title">
  <h3>STRIPE</h3>
  <p>Stripe est une plateforme sécurisée (certifiée PCI niveau 1, le niveau de sécurité le plus élevé), et s’occupe entièrement du paiement, nous n’avons à aucun moment accès à votre carte bancaire.
  Nous avons choisi Stripe, pour sa sécurité, pour son côté pratique et bien plus simple que PayPal.</p>
</div>
<div class="container">
  <div class="row">
    <div class="products">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <div class="card">
              <div class="card-content">
                
                <% product = @products.first %>
                <div class="card-title">
                  <h3><%= product.name %></h3>
                </div>
                <div class="card-description">
                  <p><%= product.description %></p>
                  <p class="centrer">Prix: <strong><%= humanized_money_with_symbol(product.price) %></strong></p>
                </div>
                <%= simple_form_for [@order, @products] do |f| %>
                  <%= f.collection_radio_buttons :product, @products, :product, :product %>
                  <%= f.input :email, label: "Email du payeur", placeholder: "tropsympa@gmail.com" %>
                  <p class="centrer">Le chanceux :</p>
                  <%= f.input :first_name, label: "Prénom", placeholder: "Prénom de celui qui vole" %>
                  <%= f.input :last_name, label: "Nom", placeholder: "Nom de celui qui vole" %>
                  <% if ["0001", "0002"].include? product.sku %>
                    <%= f.label :video, "Photos & vidéo (+20 euros)" %>
                    <%= f.check_box :video, as: :boolean, label: false %>
                  <% end %>
                  <hr id="cgv-relative-ref">

                  <%= f.input :cgv, as: :boolean, id: "checkbox-cgv", label: ("<abbr title='required'>*</abbr> J'ai bien pris connaissance des #{ link_to "conditions de ventes", asset_path("CGV-Lesgensdair.pdf"), :target => "_blank"}").html_safe %>
                  <%= f.hidden_field :product_sku, value: product.sku %>
                  <%= f.hidden_field :product_name, value: product.name %>
                  <br>
                  <%= f.submit 'OFFRIR', class: "pay-link"%>
                <% end %>
              </div>
          </div>
        </div>
    </div>
  </div>
</div>
<div class="introduction-title">
  <p>Si vous ne souhaitez pas payer en ligne, nous avons plusieurs solutions pour vous.
Vous pouvez nous envoyer le formulaire (<%= link_to "Télécharger ici", asset_path("bulletin-bon-cadeau-biplace-lgda-bergers.pdf"), :target => "_blank" %>) accompagné du règlement par chèque (chèque à l’ordre de « Les Gens d’Air » ).</p>
<p>Vous pouvez réglez par virement bancaire en nous envoyant un mail pour nos coordonnées bancaires.
Vous ne souhaitez pas un bon cadeau, vous pouvez payez après le vol, <%= link_to "contactez-nous par mail", "http://www.lesgensdair.com/contactez-nous/" %> avec vos coordonnées et disponibilités.</p>
</div>

<% if user_signed_in? %>
  <%= link_to destroy_user_session_path, method: :delete do %>
    <i class="fa fa-power-off" aria-hidden="true"></i>
  <% end %>
<% end %>

<abbr title="required">*</abbr>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="card">
          <div class="card-content">
            <div class="card-title">
              <h3>Récapitulatif de la commande d'un <%= @order.product_name %></h3>
            </div>
            <div class="card-description">
                  <p>Merci de nous avoir fait confiance, vous allez reçevoir un mail de confirmation de la commande.</p>
                  <br>
                  <p>Email de la personne ayant payé : <strong><%= @order.email %></strong></p>
                  <br>
                  <p>La personne qui va profiter du vol/stage est:</p>
                  <p><strong>Prénom :</strong> <%= @order.first_name %></p>
                  <p><strong>Nom :</strong> <%= @order.last_name %></p>
                  <p><strong>Vidéo :</strong> <%= @order.video ? "oui (+20€)" : "non" %></p>
                <label class="amount">
                  <p class="centrer">Montant de la commande : <%= humanized_money_with_symbol(@order.amount) %></p>
                </label>
                <p><strong>Numéro de la commance:</strong>&nbsp;<%= @order.id %></p>
                <br>
            </div>
          </div>
      </div>
    </div>
  </div>
  </div>

app/views/pages/bon.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bon cadeau | Les Gens d'Air</title>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Open+Sans:300,400" rel="stylesheet">
  </head>

  <body>
    <div id="sheet">
      <div id="img-zone">
       <div id="text-img-zone">
        <br><br><br><br><br>
        <h1>Bon Cadeau</h1>
        <h1><%= @product_name %></h1>
        <br><br><br>
        <h2>Pour la personne de : <%= @first_name %> <%= @last_name %></h2>
        <h2>Valable pour une durée de 1 an, soit jusqu'au : <%= (Date.today + 1.year).strftime("%d/%m/%Y")  %></h2>
        <% unless @product_name.match(/stage/i) %>
          <% if @video == "true"%>
            <h3>Option vidéo : incluse !</h3>
          <% else %>
            <h3>Option vidéo : non incluse <br>(mais vous pourrez choisir de l'ajouter lors de la prise de rendez-vous)</h3>
          <% end %>
        <% end %>
       </div>
      </div>
      <div id="green-rectangle">
      </div>
      <div id="logo-bon"></div>
      <div id="text-faq">
        <p>La période idéale pour voler est de début mai à fin septembre</p>
        <ul>
          <li>S'habiller chaudement</li>
          <li>Prendre de bonnes chaussures</li>
          <li>Manger léger (ou pas) avant le vol</li>
          <li>Signaler tout problème physique (besoin de courir au décollage et à l'atterrissage).</li>
          <li>Vous êtes assuré par le moniteur (diplômé d'État). Les vois se font à St-Pierre de Chartreuse sur le site de La Scia.</li>
          <li>Le rendez-vous se fera à St-Pierre. Mais il est possible que ce souit sur un autre site en fonction de la météo ou de votre demande.</li>
          <li>Dans l'idéal prenez rendez-vous par e-mail et proposez une ou deux dates.</li>
        </ul>
        <p>Les gens d'air vous recontactera pour fixer une heure et vous confirmera 2 jours avant, en fonction de la météo</p>
        <p>vincent@lesgensdair.com
          <br>
        06 72 28 55 42</p>
      </div>
    </div>
  </body>
</html>


<style>
  #sheet {
  border: 1px black;
  width: 1500px;
  display: block;
  background-color: #8AC9FD;
  position: relative;
}

#img-zone {
  height: 1430px;

  background-image: url("assets/background-para2.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center bottom;
}

#text-faq {
  position: absolute;
  left: 80px;
  bottom: 50px;
}

h1, h2, h3 {
    color: #FFFFFF;
  letter-spacing: 0;
  padding-left: 40px;
  text-shadow: #31495E 2px 2px, #31495E -2px 2px, #31495E -2px -2px, #31495E 2px -2px;
}

h1 {
  font-family: 'Kaushan Script', cursive;
  text-align: center;
  font-size: 80px;
  margin: 0px;
}

h2, h3 {
  font-family:  'Open Sans', sans-serif;
}

h2 {
  font-size: 42px;
}

h3 {
  font-size: 30px;
}


p, ul {
  font-family: 'Open Sans', sans-serif;
  color: #FFFFFF;
  letter-spacing: 0;
  font-size: 22px;
  text-shadow: #989898 1px 1px;
}

/* Rectangle: */
#green-rectangle {
  background-color: #7FBF3C;
  border: 2px solid #007900;
  height: 500px;
  /*position: absolute;*/
}


/* logo: */
#logo-bon {
  width: 300px;
  height: 250px;
  background-image: url("assets/logo.png");
  /*  app/assets/images/logo.png*/
  background-size: cover;
  background-repeat: no-repeat;
  position:absolute;
  top: 80px;
  left: 80px;
}
</style>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/payments/new.hmtl.erb
<h1>Achat d'un <%= @order.product_sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>

<!-- changer l'email, car pas de current user logged in -->

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Product"
    data-email="<%= current_user.email %>"
    data-description="Product <%= @order.product_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>">
  </script>

<% end %>

app/views/payments/new.html.erb
<%= form_tag order_payments_path(@order) do %>
  <div class="introduction-title">
    <h3>STRIPE</h3>
    <p>Stripe est une plateforme sécurisée (certifiée PCI niveau 1, le niveau de sécurité le plus élevé), et s’occupe entièrement du paiement, nous n’avons à aucun moment accès à votre carte bancaire.
    Nous avons choisi Stripe, pour sa sécurité, pour son côté pratique et bien plus simple que PayPal.</p>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="card">
            <div class="card-content">
              <div class="card-title">
                <h3>Achat d'un <%= @order.product_name %></h3>
              </div>
              <div class="card-description">
                <article>
                    <p>Email de la personne qui paye : <strong><%= @order.email %></strong></p>
                    <br>
                    <p>La personne qui va profiter du vol/stage:</p>
                    <p><strong>Prénom :</strong> <%= @order.first_name %></p>
                    <p><strong>Nom :</strong> <%= @order.last_name %></p>
                    <p><strong>Vidéo :</strong> <%= @order.video ? "oui (+20€)" : "non" %></p>
                  <label class="amount">
                    <p class="centrer">Montant à payer : <%= humanized_money_with_symbol(@order.amount) %></p>
                  </label>
                  <br>
                  <br>
                   <!-- Script js pour stripe -->
                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-label="Payer par carte"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-name="<%= @order.product_name %>"
                      data-email="<%= @order.email %>"
                      data-first_name
                      data-amount="<%= @order.amount_cents %>"
                      data-currency="<%= @order.amount.currency %>"
                      data-locale="fr">
                    </script>
                </article>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="introduction-title">
  <p>Si vous ne souhaitez pas payer en ligne, nous avons plusieurs solutions pour vous.
Vous pouvez nous envoyer le formulaire (<%= link_to "Télécharger ici", asset_path("bulletin-bon-cadeau-biplace-lgda-bergers.pdf"), :target => "_blank" %>) accompagné du règlement par chèque (chèque à l’ordre de « Les Gens d’Air » ).</p>
  <p>Vous pouvez réglez par virement bancaire en nous envoyant un mail pour nos coordonnées bancaires.
Vous ne souhaitez pas un bon cadeau, vous pouvez payez après le vol, <%= link_to "contactez-nous par mail", "http://www.lesgensdair.com/contactez-nous/" %> avec vos coordonnées et disponibilités.</p>
</div>

<% end %>

app/views/products/index.html.erb
<div class="introduction-title">
  <h3>STRIPE</h3>
  <p>Stripe est une plateforme sécurisée (certifiée PCI niveau 1, le niveau de sécurité le plus élevé), et s’occupe entièrement du paiement, nous n’avons à aucun moment accès à votre carte bancaire.
  Nous avons choisi Stripe, pour sa sécurité, pour son côté pratique et bien plus simple que PayPal.</p>
</div>
<div class="container">
  <div class="row">
    <div class="products">
      <% @products.each do |product| %>
        <div class="col-xs-12 col-sm-6">
          <div class="card">
              <div class="card-content">
                <div class="card-title">
                  <h3><%= product.name %></h3>
                </div>
                <div class="card-description">
                  <p><%= product.description %></p>
                  <p class="centrer">Prix: <strong><%= humanized_money_with_symbol(product.price) %></strong></p>
                </div>
                <%= simple_form_for @order do |f| %>
                  <%= f.input :email, label: "Email du payeur", placeholder: "tropsympa@gmail.com" %>
                  <p class="centrer">Le chanceux :</p>
                  <%= f.input :first_name, label: "Prénom", placeholder: "Prénom de celui qui vole" %>
                  <%= f.input :last_name, label: "Nom", placeholder: "Nom de celui qui vole" %>
                  <% if ["0001", "0002"].include? product.sku %>
                    <%= f.label :video, "Photos & vidéo (+20 euros)" %>
                    <%= f.check_box :video, as: :boolean, label: false %>
                  <% end %>
                  <hr id="cgv-relative-ref">

                  <%= f.input :cgv, as: :boolean, id: "checkbox-cgv", label: ("<abbr title='required'>*</abbr> J'ai bien pris connaissance des #{ link_to "conditions de ventes", asset_path("CGV-Lesgensdair.pdf"), :target => "_blank"}").html_safe %>
                  <%= f.hidden_field :product_sku, value: product.sku %>
                  <%= f.hidden_field :product_name, value: product.name %>
                  <br>
                  <%= f.submit 'OFFRIR', class: "pay-link"%>
                <% end %>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="introduction-title">
  <p>Si vous ne souhaitez pas payer en ligne, nous avons plusieurs solutions pour vous.
Vous pouvez nous envoyer le formulaire (<%= link_to "Télécharger ici", asset_path("bulletin-bon-cadeau-biplace-lgda-bergers.pdf"), :target => "_blank" %>) accompagné du règlement par chèque (chèque à l’ordre de « Les Gens d’Air » ).</p>
<p>Vous pouvez réglez par virement bancaire en nous envoyant un mail pour nos coordonnées bancaires.
Vous ne souhaitez pas un bon cadeau, vous pouvez payez après le vol, <%= link_to "contactez-nous par mail", "http://www.lesgensdair.com/contactez-nous/" %> avec vos coordonnées et disponibilités.</p>
</div>

<% if user_signed_in? %>
  <%= link_to destroy_user_session_path, method: :delete do %>
    <i class="fa fa-power-off" aria-hidden="true"></i>
  <% end %>
<% end %>

<abbr title="required">*</abbr>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>